language: generic

addons:
  apt:
    packages:
    - curl
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

install:
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview2-003121 --install-dir ./.vscode/cli

script:
  - ./.vscode/cli/dotnet --info
  - ./.vscode/cli/dotnet restore
  - ./.vscode/cli/dotnet build */*/project.json
  - ./.vscode/cli/dotnet test test/XConsoleTest
  - ./.vscode/cli/dotnet test example/LibraryTest
